[api]
ask_url = "https://hgut2hrxz0.execute-api.ap-northeast-1.amazonaws.com/prod/ask"
history_url = "https://hgut2hrxz0.execute-api.ap-northeast-1.amazonaws.com/prod/get-history"
get_answer_url = "https://hgut2hrxz0.execute-api.ap-northeast-1.amazonaws.com/prod/get-answer"
delete_url = "https://your-api.com/delete-answer"
admin_passcode = "sp2025admin"
[bedrock]
api_base = "https://hgut2hrxz0.execute-api.ap-northeast-1.amazonaws.com/prod"
s3_bucket = "bedrock-kb-cloudops"