# agents/orchestrator.py

from agents.owasp_agent import handle_owasp_question
from agents.assignment_agent import handle_assignment_question

def route_question(question: str, topic: str) -> str:
    """
    Routes the incoming question to the appropriate agent based on topic.

    Args:
        question (str): The user's question.
        topic (str): The topic to route (e.g., 'OWASP', 'Assignment').

    Returns:
        str: The answer generated by the appropriate agent.
    """
    topic = topic.strip().lower()

    if topic == "owasp":
        return handle_owasp_question(question)
    elif topic == "assignment":
        return handle_assignment_question(question)
    else:
        return f"Sorry, no agent available for topic '{topic}'."